/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AbstractProductA;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Maja
 */
public class Panel2 extends Panel {

    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSifraRezervacije = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBrojOsoba = new javax.swing.JTextField();
        txtSifraRezervacije = new javax.swing.JTextField();
        btnNadji = new javax.swing.JButton();
        lblIme = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        lblNazivHotela = new javax.swing.JLabel();
        lblDatumPocetka = new javax.swing.JLabel();
        lblDatumZavrsetka = new javax.swing.JLabel();
        btnKreiraj = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        txtPoruka = new javax.swing.JTextField();
        comboBoxNazivHotela = new javax.swing.JComboBox<>();
        datumZavrsetkaPicker = new datechooser.beans.DateChooserCombo();
        datumPocetkaPicker = new datechooser.beans.DateChooserCombo();
        jLabelBackground = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(540, 405));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSifraRezervacije.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblSifraRezervacije.setText("Sifra rezervacije:");
        jPanel1.add(lblSifraRezervacije, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 38, 195, -1));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        jLabel1.setText(" Broj osoba:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, 120, -1));
        jPanel1.add(txtBrojOsoba, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 160, -1));

        txtSifraRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraRezervacijeActionPerformed(evt);
            }
        });
        txtSifraRezervacije.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSifraRezervacijeKeyPressed(evt);
            }
        });
        jPanel1.add(txtSifraRezervacije, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 37, 160, -1));

        btnNadji.setFont(new java.awt.Font("Verdana Pro Light", 1, 12)); // NOI18N
        btnNadji.setText("Nadji");
        jPanel1.add(btnNadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 86, -1));

        lblIme.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblIme.setText("Ime i prezime:");
        jPanel1.add(lblIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 207, -1));

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });
        txtIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImeKeyPressed(evt);
            }
        });
        jPanel1.add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 155, -1));

        lblNazivHotela.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblNazivHotela.setText("Naziv hotela:");
        jPanel1.add(lblNazivHotela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 207, -1));

        lblDatumPocetka.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblDatumPocetka.setText("Datum pocetka rezervacije:");
        jPanel1.add(lblDatumPocetka, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 207, -1));

        lblDatumZavrsetka.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblDatumZavrsetka.setText("Datum zavrsetka rezervacije:");
        jPanel1.add(lblDatumZavrsetka, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnKreiraj.setFont(new java.awt.Font("Verdana Pro Light", 1, 12)); // NOI18N
        btnKreiraj.setText("Kreiraj");
        jPanel1.add(btnKreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 86, -1));

        btnPromeni.setFont(new java.awt.Font("Verdana Pro Light", 1, 12)); // NOI18N
        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(btnPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 86, -1));

        btnObrisi.setFont(new java.awt.Font("Verdana Pro Light", 1, 12)); // NOI18N
        btnObrisi.setText("Obrisi");
        jPanel1.add(btnObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 86, 22));

        lblPoruka.setFont(new java.awt.Font("Verdana Pro Light", 1, 14)); // NOI18N
        lblPoruka.setText("Poruka:");
        jPanel1.add(lblPoruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 195, -1));

        txtPoruka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtPoruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 273, -1));

        comboBoxNazivHotela.setFont(new java.awt.Font("Verdana Pro Light", 1, 12)); // NOI18N
        comboBoxNazivHotela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Zvezda", "Hotel Beli bor", "Hotel Zelenkada", "Hotel Planinac" }));
        comboBoxNazivHotela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNazivHotelaActionPerformed(evt);
            }
        });
        comboBoxNazivHotela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBoxNazivHotelaKeyPressed(evt);
            }
        });
        jPanel1.add(comboBoxNazivHotela, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 155, -1));
        jPanel1.add(datumZavrsetkaPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));
        jPanel1.add(datumPocetkaPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/summer.jpg"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 580, 440));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 570, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void txtSifraRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraRezervacijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraRezervacijeActionPerformed

    private void comboBoxNazivHotelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNazivHotelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxNazivHotelaActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void txtSifraRezervacijeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSifraRezervacijeKeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtIme.requestFocusInWindow();
            } 
    }//GEN-LAST:event_txtSifraRezervacijeKeyPressed

    private void txtImeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeKeyPressed
                if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                comboBoxNazivHotela.requestFocusInWindow();
            }
    }//GEN-LAST:event_txtImeKeyPressed

    private void comboBoxNazivHotelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxNazivHotelaKeyPressed
                if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                datumPocetkaPicker.requestFocusInWindow();
            }
    }//GEN-LAST:event_comboBoxNazivHotelaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnNadji;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<String> comboBoxNazivHotela;
    private datechooser.beans.DateChooserCombo datumPocetkaPicker;
    private datechooser.beans.DateChooserCombo datumZavrsetkaPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDatumPocetka;
    private javax.swing.JLabel lblDatumZavrsetka;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblNazivHotela;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JLabel lblSifraRezervacije;
    private javax.swing.JTextField txtBrojOsoba;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPoruka;
    private javax.swing.JTextField txtSifraRezervacije;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getSifraRezervacije() {
        return txtSifraRezervacije.getText();
    }

   

    @Override
    public String getImePrezime() {
        return txtIme.getText();
    }

    @Override
    public String getNazivHotela() {
        return comboBoxNazivHotela.getSelectedItem().toString();
    }

    @Override
    public Date getDatumPocetka() {
    return datumZavrsetkaPicker.getSelectedDate().getTime();
    }

    @Override
    public Date getDatumZavrsetka() {
    return datumZavrsetkaPicker.getSelectedDate().getTime();
    }

    @Override
    public void setSifraRezervacije(String sifraRezervacije) {
        txtSifraRezervacije.setText(sifraRezervacije);
    }

    @Override
    public void setImePrezime(String imePrezime) {
        txtIme.setText(imePrezime);    }

    @Override
    public void setNazivHotela(String nazivHotela) {
        comboBoxNazivHotela.setSelectedItem(nazivHotela);    }

    @Override
    public void setDatumPocetka(Date datumPocetka) {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(datumPocetka);
        datumPocetkaPicker.setSelectedDate(gc);
}

    @Override
    public void setDatumZavrsetka(Date datumZavrsetka) {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(datumZavrsetka);
        datumZavrsetkaPicker.setSelectedDate(gc);
}

    @Override
    public void setPoruka(String Poruka) {
        txtPoruka.setText(Poruka);
    }

    @Override
    public JButton getKreiraj() {
        return btnKreiraj;
    }

    @Override
    public JButton getPromeni() {
        return btnPromeni;    }

    @Override
    public JButton getObrisi() {
        return btnObrisi;    }

    @Override
    public JButton getNadji() {
        return btnNadji;    }

    @Override
    public JTextField getSifraRezervacije1() {
        return txtSifraRezervacije;
    }

    @Override
    public String getBrojOsoba() {
        return txtBrojOsoba.getText();
    }

    @Override
    public void setBrojOsoba(String brojOsoba) {
        txtBrojOsoba.setText(brojOsoba);
    }
}
